### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by sidhantsetia**
Update big translate to use oodt 0.11-SNAPSHOT

### CODE REVIEW

**Comment by chrismattmann** [comment]
thanks @sidhantsetia !

**Comment by chrismattmann** [comment]
so does it work now for you? @sidhantsetia

**Comment by sidhantsetia** [comment]
Yes Professor. The build is successful now. @chrismattmann

**Comment by chrismattmann** [comment]
great @sidhantsetia

**Pull request merged**
